version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    run-as: root
    build:
      commands:
        - echo Build Starting on `date`
        - chmod +x ./gradlew
        - ./greadlew build --stacktrace --task test
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pwd
artifacts:
  files:
    - apps/lolmatch/lolmatch-1.0.jar
