spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.25.204:3306/lolmatch_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: lolmatch
    password: lolmatch12#$
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: local
  thymeleaf:
    cache: true
    suffix: .html

jwt:
  secretKey: lolMatchSecretKeyasdfasdfsadfwerasdqwesadfasdfsadfcxzvaasdf
  accessExpireTime: 1440
  refreshExpireTime: 1440

server:
  port: 8081
